services:
  wss:
    build:
      context: ./SocketServer
      dockerfile: Dockerfile
    container_name: socket-server-chatlamp
    ports:
      - 3000:3000

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: api-chatlamp
    ports:
      - 3001:3001
      
    